[package]
name = "libzim-rs"
version = "0.1.0"
edition = "2024"
authors = ["arthrp"]
license = "GPL-3.0-only"
description = "Library to read/write zim files. Supports only zim 6.3+"
keywords = ["zim", "libzim"]
homepage = "https://github.com/arthrp/libzim-rs"
repository = "https://github.com/arthrp/libzim-rs"
readme = "../README.md"

[dependencies]
md-5 = "0.11"
zstd = "0.13"
