name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build libzim-rs
      run: cargo build --verbose --manifest-path libzim-rs/Cargo.toml
    - name: Test libzim-rs
      run: cargo test --verbose --manifest-path libzim-rs/Cargo.toml
    - name: Build ziminfo
      run: cargo build --verbose --manifest-path ziminfo/Cargo.toml
    - name: Test ziminfo
      run: cargo test --verbose --manifest-path ziminfo/Cargo.toml
