name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting libzim-rs
      run: cargo fmt --manifest-path libzim-rs/Cargo.toml --check
    - name: Check formatting ziminfo
      run: cargo fmt --manifest-path ziminfo/Cargo.toml --check

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Build libzim-rs
      run: cargo build --verbose --manifest-path libzim-rs/Cargo.toml
    - name: Test libzim-rs
      run: cargo test --verbose --manifest-path libzim-rs/Cargo.toml
    - name: Build ziminfo
      run: cargo build --verbose --manifest-path ziminfo/Cargo.toml
    - name: Test ziminfo
      run: cargo test --verbose --manifest-path ziminfo/Cargo.toml
